# Site settings
title: Wenqin Blog
SEOTitle: 问琴的博客 | Wenqin Blog
header-img: img/home-bg.jpg
email: impossiblepjm@gmail.com
description: "这里是 @Wenqin问琴 的个人博客，与你一起品尝世界~"
keyword: "问琴, Wenqin问琴, Wenqin, 问琴的博客, Wenqin Blog, 博客, 个人网站, 互联网, Web, BigData, 大数据, openGauss, Oracle"
url: "https://www.881119.xyz" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username: uniqueatom
zhihu_username: pan-jia-qian-9
github_username: impossiblepjm
x_username: really_darkful
bilibili_username: 45494855
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncgem install jekyll bundlergem install jekyll bundleromment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true  # 代码块行数显示
      start_line: 1

# Disqus settings
# disqus_username: unique_atom

# Giscus settings
giscus_comment: true

# Analytics settings
# Baidu Analytics
ba_track_id: [d5d8d224f2a25f15bc0adde7c78b08b5]

# Google Analytics
ga_track_id: "G-ED5BZBFN9G" # Format: UA-xxxxxx-xx
ga_domain: impossiblepjm.github.io

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "无法飞翔的翅膀，还会有意义吗?"
sidebar-avatar: https://hangzhou666666.oss-cn-hangzhou.aliyuncs.com/photos/Air%E7%A5%9E%E5%B0%BE%E5%85%B3%E5%B2%AD.jpg # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  [
    { title: "哪一个才是真正的我?", href: "https://www.1119888.xyz/" }
    # { title: "Ebn Zhang", href: "https://ebnbin.dev/" },
  ]
